<h2>Anime Collaborative Recommendation System</h2>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/Users/owais/Jupyter Notebook/archive-2/rating.csv')

In [3]:
df

         user_id  anime_id  rating
0              1        20      -1
1              1        24      -1
2              1        79      -1
3              1       226      -1
4              1       241      -1
...          ...       ...     ...
7813732    73515     16512       7
7813733    73515     17187       9
7813734    73515     22145      10
7813735    73516       790       9
7813736    73516      8074       9

[7813737 rows x 3 columns]

In [4]:
len(df['anime_id'].unique())

11200

In [140]:
# rare_movies

In [141]:
# len(rare_movies)

In [7]:
11200-9480

1720

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7813737 entries, 0 to 7813736
Data columns (total 3 columns):
 #   Column    Dtype
---  ------    -----
 0   user_id   int64
 1   anime_id  int64
 2   rating    int64
dtypes: int64(3)
memory usage: 178.8 MB

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
user_id,7813737.0,36727.956745,20997.946119,1.0,18974.0,36791.0,54757.0,73516.0
anime_id,7813737.0,8909.072104,8883.949636,1.0,1240.0,6213.0,14093.0,34519.0
rating,7813737.0,6.144030,3.727800,-1.0,6.0,7.0,9.0,10.0

In [10]:
df = df.replace(np.nan, 0)

In [11]:
x=pd.DataFrame(df["anime_id"].value_counts())
x.isna().sum()
x

          count
anime_id
1535      39340
11757     30583
16498     29584
1575      27718
226       27506
...         ...
12781         1
12767         1
12765         1
12763         1
30738         1

[11200 rows x 1 columns]

In [12]:
# rating_counts = pd.DataFrame(df["anime_id"])
# rating_counts.reset_index(drop=True)
# rating_counts['anime_id'] = pd.DataFrame(df['anime_id'].value_counts())
rating_counts = pd.DataFrame(df['anime_id'].value_counts())

In [13]:
# rare_movies = rating_counts[rating_counts["anime_id"] <= 1000].index
# common_movie = df[~df["anime_id"].isin(rare_movies)]
rating_counts.columns

Index(['count'], dtype='object')

In [123]:
type(rare_movies)

pandas.core.indexes.base.Index

In [136]:
# (df[df["anime_id"].isin(rare_movies)])

In [139]:
# cm=df[~df["anime_id"].isin(rare_movies)]

In [137]:
# len(cm['anime_id'].unique())

In [138]:
# cm

In [18]:
# rare_movies

In [19]:
rare_movies = rating_counts[rating_counts["count"] <= 1000].index
common_movie = df[~df["anime_id"].isin(rare_movies)]

In [20]:
common_movie = common_movie.pivot_table(index = "user_id", columns = "anime_id")

common_movie.head()

         rating                                                        ...
anime_id  1     5     6     7     15    16    18    19    20    22     ...
user_id                                                                ...
1           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  -1.0   NaN  ...  \
2           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
3           NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   8.0   NaN  ...
4           NaN   NaN  -1.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...
5           NaN   NaN   8.0   NaN   6.0   NaN   6.0   NaN   6.0   5.0  ...


anime_id 32379 32380 32438 32542 32729 32828 32935 32998 33028 34240
user_id
1          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
3          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
4          NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
5          NaN   NaN   NaN   NaN   NaN   7.0   NaN   NaN   NaN   NaN

[5 rows x 1720 columns]

In [21]:
common_movie = common_movie.replace(np.nan, 0)

In [22]:
common_movie

         rating                                                        ...
anime_id  1     5     6     7     15    16    18    19    20    22     ...
user_id                                                                ...
1           0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  -1.0   0.0  ...  \
2           0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
3           0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   8.0   0.0  ...
4           0.0   0.0  -1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
5           0.0   0.0   8.0   0.0   6.0   0.0   6.0   0.0   6.0   5.0  ...
...         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...
73512       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
73513       9.0   8.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
73514       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...
73515      10.0  10.0  10.0   0.0   0.0   0.0   0.0   9.0   0.0   0.0  ...
73516       0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...


anime_id 32379 32380 32438 32542 32729 32828 32935 32998 33028 34240
user_id
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
5          0.0   0.0   0.0   0.0   0.0   7.0   0.0   0.0   0.0   0.0
...        ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
73512      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73513      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73514      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73515      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73516      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[73340 rows x 1720 columns]

In [51]:
common_movie_reset['user_id'].unique()

array([    1,     2,     3, ..., 73514, 73515, 73516])

In [52]:
len(common_movie_reset['user_id'].unique())

73340

In [29]:
my_ratings = np.array(common_movie.iloc[4])

In [156]:
already_watched=pd.DataFrame(common_movie.iloc[4][common_movie.iloc[4] != 0])

In [157]:
# common_movie.iloc[4][common_movie.iloc[4] != 0]

In [158]:
already_watched.reset_index(inplace=True)
already_watched.set_index(['anime_id'], inplace=True)
already_watched.drop('level_0',axis=1)

            5
anime_id
6         8.0
15        6.0
18        6.0
20        6.0
22        5.0
...       ...
31240     8.0
31636    -1.0
31964    -1.0
32182     9.0
32828     7.0

[400 rows x 1 columns]

In [159]:
aw=already_watched.index

In [ ]:
# (common_movie.iloc[1721]) #observation

In [30]:
my_ratings

array([0., 0., 8., ..., 0., 0., 0.])

<h3>Vector of favorit anime</h3>

In [ ]:
# list_movie = df["anime_id"]
list_movie = cm["anime_id"]
list_m=sorted(set(list_movie))

In [ ]:
list_movie

In [ ]:
len(list_m)

In [ ]:
list_m

In [ ]:
#example of anime favorite anime list
# anime_id_favorite = [32379,6,5,1,32438]
anime_id_favorite = [1,5,6,7,15]
#example of vote of each anime
vote = [6,4,8,-1,10] 
#creating the vector of favorit anime 
a = 1720
b = len(anime_id_favorite)
vector = []
for i in range(a):
    for j in range(b):
        if anime_id_favorite[j] == list_m[i]:
            vector.append(vote[j])
            break
        elif j==b-1:
            vector.append(0)

In [ ]:
vector = np.array(vector).T
len(vector)

In [ ]:
vector

<h2>Cosine Similarity</h2>

In [31]:
from scipy.spatial import distance

In [33]:
# len(vector)

In [34]:
len(common_movie.iloc[[2]].T)

1720

In [35]:
d = len(common_movie)
score = []
for i in range(d):
    score.append(distance.cosine(np.squeeze(common_movie.iloc[[i]]), my_ratings))

# eg = np.squeeze(common_movie.iloc[[i]])
# eg.shape

In [36]:
score

[1.0663423124373064,
 1.0081171394848936,
 0.7752643031454982,
 1.1793651366751645,
 0,
 1.0710171014012735,
 0.7208359085415273,
 0.9496816520064016,
 0.9692578411326042,
 1.006271298563887,
 0.9136201692776561,
 0.9212054478980346,
 1.2668064634551697,
 0.8283724243872302,
 1.0,
 0.9732170105270752,
 0.667644787441699,
 0.9507532527287035,
 0.8835500754803396,
 0.98775902358261,
 0.8022473248351534,
 0.965080318795035,
 0.8558041466095413,
 0.9302888827122032,
 0.8867106954142622,
 1.0454040187964675,
 0.8392542832961136,
 0.902472808084771,
 0.7471353233566108,
 0.9074679954931069,
 0.8556216596325039,
 0.944696098782017,
 0.9103073205728243,
 0.9456505548381843,
 1.0596702204087756,
 1.000970455608218,
 0.8900170154593897,
 0.7314840081605104,
 0.9262329838633723,
 0.8962954486462924,
 0.8067767266264004,
 0.9851748145481759,
 0.7585054324734527,
 0.8201734485172012,
 0.9905775870646253,
 0.7002043563275343,
 0.8996876355078542,
 0.891369453002009,
 1.0167339117370437,
 0.7715056962052254,
 0.8597104166811484,
 0.847666227946847,
 0.9231978874197193,
 1.2918738422168554,
 0.8691829066295853,
 0.8882908898433832,
 0.9447303415522683,
 0.9621649685986069,
 1.0,
 0.9526693501398367,
 0.95045204949818,
 0.8328312836702803,
 1.0,
 0.9542185159229583,
 0.9558936886777952,
 0.9534858819234754,
 0.9577188291455262,
 0.9074369446646527,
 0.9521405588538392,
 0.9077735233978125,
 0.888271302605841,
 0.9093005653535811,
 0.7718308414083965,
 1.0,
 0.8632689020632128,
 1.0,
 0.7755187172889995,
 0.9428738331771607,
 0.8455183585874518,
 0.7742228922538699,
 0.8027043195403849,
 0.8858875297771713,
 1.0,
 0.9251500055518552,
 0.921098917459283,
 1.007137571322094,
 0.8160294271892696,
 0.884605255436426,
 1.1004034704222627,
 0.9962336927041759,
 0.9618598893642571,
 0.9569501765344746,
 0.7510007739866462,
 0.8886916841621422,
 0.8409553340532973,
 0.9574923235413786,
 0.9079327818081289,
 0.9047420298356783,
 0.7897210993777275,
 0.9355207976906179,
 0.9347860329896507,
 0.8589637079359119,
 0.9304631184583443,
 0.8985765632041127,
 0.946654236336455,
 0.8297157586622553,
 0.9210387044907318,
 0.834771601846791,
 0.9009362993016944,
 0.898942959213102,
 0.9258566357445528,
 0.9393345597008568,
 1.0,
 1.0,
 0.9300218236450896,
 0.9610658065021451,
 0.9129017665205831,
 0.9190834101967177,
 1.0,
 0.7911912009355203,
 0.8797234486754848,
 0.8386015641223559,
 0.72812868722797,
 0.9203674079242683,
 0.9044445152397765,
 0.8695166145850531,
 0.8345694809708178,
 0.8628459196580721,
 0.7152819936417318,
 0.8207798312697013,
 1.0,
 0.8667896222306569,
 1.1188343398855254,
 0.8972146167062134,
 0.9170893291152051,
 0.987109384404485,
 0.988819184917762,
 0.965599346848559,
 0.7865582527788283,
 0.8947749957116113,
 0.8012798904887369,
 0.9548073026611305,
 1.0124479795680603,
 0.8793849910443432,
 1.1199446126732602,
 0.8697585349389586,
 0.8841222321576836,
 0.6225527886204192,
 0.9824006355253991,
 0.9570312813482835,
 1.060797320555316,
 0.808662138450284,
 0.9032173725195213,
 0.982700420860256,
 0.7997993932741823,
 0.9162727580547854,
 1.070044631233338,
 0.904885698046674,
 0.8790825974992588,
 0.8490396488559802,
 0.9475341905555182,
 0.7837931689029702,
 0.8791960713768147,
 0.8653955776752932,
 0.8474765900847642,
 0.919465781027103,
 0.9531937782496844,
 0.8095154771324322,
 0.8234413372738263,
 0.7655319429931488,
 1.0874874591166825,
 0.8084944226921154,
 0.8574145517446415,
 0.9517901534811234,
 0.9747492442794683,
 0.7857179592120438,
 0.9260492304680734,
 0.9588538010777333,
 0.94967310128334,
 0.9366169710164515,
 1.0333630725959422,
 0.7826062530491348,
 0.8873988482749537,
 0.9314357598029123,
 0.8722296114244469,
 0.8833299670676332,
 1.1018793976314933,
 0.7487691107133989,
 0.8521083970341002,
 0.771207583469818,
 0.9139302746909191,
 0.9423197133365112,
 0.9264608057628623,
 0.9385156822652083,
 0.9366776484091173,
 0.9172448901779856,
 1.1075417143803454,
 0.9645931140947537,
 0.9059904401549853,
 0.903632119254615,
 0.760324685660082,
 0.9929788991735985,
 0.9196681418712332,
 0.9522093718889205,
 1.0,
 0.9167993202798417,
 0.8725229300371825,
 0.9160999462260473,
 0.6835916902041759,
 0.8637211408506711,
 1.0,
 0.9299734428742766,
 0.8444607860330053,
 0.9380787835581388,
 0.9165721918358788,
 0.8837688153253255,
 0.9835215828349658,
 0.8670192731351596,
 0.9423082881038225,
 1.0347949873407272,
 0.8565531641712159,
 1.0,
 0.9212057718598701,
 0.8935385783708051,
 0.6846438255067127,
 0.9721401431142614,
 0.7999991029116591,
 0.963250734782728,
 0.8937584812285224,
 0.8241977586071046,
 0.9738035331401177,
 0.7928630502508712,
 0.8461510379110839,
 0.6888847157264473,
 0.8890596211019128,
 1.0232388877509624,
 1.0,
 0.9548913031042199,
 1.1703355817025027,
 0.8801171506687824,
 0.8208506073172783,
 0.9446034806207642,
 0.7056695629514542,
 0.7469078102020337,
 0.9081438654380608,
 0.9067085783436335,
 0.7291799730404317,
 0.8624331408603215,
 0.6907349442967526,
 0.9259169653830547,
 0.7955496687706052,
 0.8243294543912725,
 0.9491749175762626,
 0.9133738932568632,
 0.7411975362088374,
 0.9713423878860492,
 0.9280108847277192,
 0.9954456060937191,
 0.883683890009086,
 0.7747214926260885,
 0.8583829820037642,
 0.8394934911865063,
 0.9472529162864403,
 0.9533264479618624,
 0.9357315959691159,
 1.0312882434605577,
 0.8728169272667776,
 0.8302475119168526,
 1.0606664936803072,
 0.7146963178904044,
 0.8387587393567848,
 0.7842115864662016,
 1.2090640995762174,
 0.8934824414361875,
 0.8752405409134182,
 0.9346194052763853,
 0.9291738045873894,
 0.9370600863634302,
 0.8266756193028346,
 0.8809405709830721,
 0.7031311996547931,
 0.9727575887221195,
 0.9029180502814486,
 1.2736598460687498,
 0.9365520581514912,
 1.0025132302643063,
 0.8156977119330739,
 1.0685514240945664,
 0.8999758035672294,
 0.8951505843781776,
 0.886055294259193,
 0.7527071711757976,
 0.7224081444917192,
 0.8604897790457471,
 0.7514937761484622,
 0.88932166387969,
 0.7814729785701021,
 0.9631914240751124,
 0.8155000923456819,
 0.8104685622075252,
 1.060033793356653,
 0.8244854236736225,
 0.9875003872312339,
 0.9652135369910907,
 0.924815363158651,
 0.9662975054729528,
 0.870866966546785,
 0.8717152115788754,
 1.037935713886193,
 0.9381873077459969,
 0.8694798925929983,
 0.9927540036655167,
 0.9077221826674875,
 0.8866438329551889,
 0.9118314665243697,
 0.768911350214579,
 0.9438646900594584,
 0.9391074604034803,
 0.73862151041286,
 0.7145341077760117,
 0.8031509751991364,
 0.9223884528167421,
 0.8911424729953279,
 0.8864589895071013,
 0.747459066319154,
 1.0017259712098607,
 1.0454738174830178,
 0.9078997746227802,
 0.9735384522495604,
 0.908908639794797,
 0.788294331337591,
 0.9858531042802742,
 0.9060683211125712,
 0.8873617998180119,
 0.8399778361573313,
 0.9390596168274112,
 1.0580543969205098,
 0.8934907673751337,
 0.9168939896302813,
 0.7318157270203376,
 0.9180394125052387,
 0.8720767380228155,
 0.9297862419435242,
 0.8177272182342684,
 0.9672991840705623,
 1.0,
 0.8352654445343117,
 0.7561396283591174,
 0.7802397144441746,
 1.0,
 0.7267152784753919,
 0.8876182583170087,
 0.7911153999517982,
 1.0,
 0.9572769097156464,
 0.8612712747029034,
 0.9007253878976437,
 0.8728369660975478,
 0.9758645503792638,
 0.8181604921714538,
 1.0,
 0.7568802913969854,
 0.8673360464320014,
 0.9247550908621844,
 0.9865355145715279,
 0.8690686424016095,
 0.9307247821579206,
 0.8748006648924179,
 0.8634044329732575,
 0.828304222594999,
 1.2673017303709888,
 0.800115923325294,
 1.0009953141428747,
 0.8880899135948698,
 0.9068951760016011,
 0.9816770598527265,
 1.0,
 0.7265860016415627,
 0.9352891527937108,
 1.2072515771731829,
 0.8609052381907598,
 0.8912087434265319,
 0.8787142790917453,
 0.7930987053335795,
 0.926340756770885,
 0.7718359820419542,
 0.9897526137108681,
 0.8981003942164419,
 0.8491515308548486,
 0.9674977747926512,
 0.6130547945973153,
 0.8309393728185192,
 0.962507766905006,
 0.7487589668118182,
 1.1250169406990846,
 0.9219861373359806,
 1.0752497317650211,
 1.041414318627643,
 0.7723117946137912,
 0.850164008222565,
 1.0,
 0.9071420915364944,
 0.8587385544579516,
 0.8023901594637666,
 0.9286811505413861,
 1.3079774733908636,
 0.9763109160227865,
 0.862906588834586,
 0.9124315544639974,
 0.965078668011599,
 0.9542797736647552,
 0.9845610770582693,
 0.9941078665426347,
 0.9253123223250095,
 0.767859686996855,
 0.8035798622942885,
 0.7724220447127167,
 0.8463478125233548,
 0.8387389839468025,
 0.8021411242086757,
 0.9639871892772836,
 0.8741226913489535,
 0.9561681714281217,
 0.8963193501012889,
 0.9646585229277044,
 0.7699998569293385,
 0.7020176167399432,
 0.9826229379205614,
 0.9350164112616604,
 0.9372130769523513,
 0.8973876076562426,
 0.8189378446868684,
 0.9013501900968265,
 0.8529625198727677,
 0.8990782342422527,
 1.0803322836795417,
 0.7155083957132917,
 0.8527484053401221,
 0.9541479109648646,
 0.8509083319686583,
 0.9729666641248086,
 0.940959385703701,
 0.8059431606671204,
 0.8004348356603376,
 0.7298322477271885,
 0.8962853569153298,
 0.9225187556191154,
 0.9087839743808436,
 0.9864958451245509,
 0.9375128156753936,
 1.0723098907708672,
 0.9560314127411159,
 0.9724797466755495,
 0.804865652305331,
 0.8943506549296585,
 1.0,
 0.9437200763693626,
 0.8096452330415717,
 0.7229762955752134,
 0.7693545737900086,
 0.7977030596603549,
 0.8264263499099792,
 1.0,
 0.9355665669806202,
 0.9039524641035599,
 1.1266094883759368,
 0.9545182036499993,
 0.8354109688680308,
 0.9567486046280524,
 0.9469150198093986,
 1.0,
 0.9505687911562897,
 0.9782620109965502,
 0.8878871508693242,
 1.0648837675873222,
 1.2565929178039548,
 0.6704913480696721,
 0.9050863132261852,
 0.9910076427848552,
 0.9251964281127651,
 0.8296628819353257,
 0.936976044965768,
 0.9613248571424603,
 0.8173211848514708,
 0.9431121996873038,
 0.9087310450324699,
 0.8791207314782721,
 0.7906978013376056,
 0.8884530149540479,
 0.9897526137108681,
 0.6815006220870328,
 1.1656572745105716,
 0.721323099198558,
 0.8590425492000126,
 0.86186755506508,
 0.7451422276026549,
 1.030897032184439,
 1.0,
 0.7445736303907386,
 0.7766330761325224,
 0.9239214641620849,
 0.8810911520587301,
 1.0636449936549166,
 0.8902596801316403,
 1.0896646300299047,
 0.8048033016530938,
 0.816354510850646,
 0.9692578411326042,
 0.8501108689468417,
 0.7830340537911618,
 0.9586310610483316,
 0.8952085035356805,
 0.805653510300776,
 0.995816522065739,
 0.8509305425774676,
 0.9167304084012666,
 0.9047773478128669,
 0.7880487532006166,
 0.9589727632997321,
 0.9152611052237852,
 0.9600971103350998,
 0.9791468728144221,
 1.1607558724107574,
 0.7927757507991424,
 0.9509778599405525,
 0.953365510770377,
 0.6817370871269333,
 0.7668585950010229,
 0.8503601338982402,
 1.099028616571271,
 0.8414390401156149,
 0.8513488771162777,
 0.9300978709634532,
 1.0,
 1.1542441344937886,
 0.8644957222991082,
 0.9353458198863893,
 0.6577060759582545,
 0.7496980831414373,
 0.8706191775204088,
 0.915160102679627,
 0.9307278626891277,
 0.8555210515342194,
 0.9500535364819651,
 0.7009119028031505,
 0.7625096777836559,
 0.9692578411326042,
 0.9771495332708643,
 0.7250060385686017,
 0.9501849384501992,
 0.7603623005385627,
 0.9880787021204879,
 0.9692578411326042,
 0.8260362290006753,
 0.9460286648838901,
 0.9212370377052994,
 0.7468762441139392,
 0.9442570100765902,
 0.8195214649873246,
 0.7782235189993761,
 0.7677637281697328,
 0.8223377291635341,
 0.7936281803199745,
 0.817712733327632,
 0.6537384902748482,
 0.8612748229760392,
 0.9666674493719438,
 0.859272573074779,
 0.8195094112321641,
 0.8097862342878984,
 0.7040899690453928,
 1.2327539702135024,
 1.0,
 0.8804662350163734,
 0.9465895081430754,
 0.7144135330553653,
 0.885695306904847,
 0.8621297785041712,
 0.8130334457523762,
 0.9515417201973618,
 1.0,
 1.0014109183306308,
 0.7513812152622924,
 0.9602810009612832,
 0.9130848236479923,
 0.9005161233151606,
 1.1693810457069644,
 0.8870826571900023,
 0.9431261122642935,
 0.8775385038364976,
 0.6764234133213385,
 0.9282682959760763,
 0.8134345386642163,
 0.9318423871839632,
 1.0312632495195746,
 0.728933524043001,
 0.7721762856408383,
 0.9484787795817216,
 0.948904004015029,
 0.9384701551817878,
 0.9555476885546574,
 0.8224684665297468,
 0.9226647011570699,
 0.8203475729098778,
 0.9549482622578386,
 0.8991230301979126,
 0.9270200991837435,
 0.8870264322930217,
 0.7795591353192796,
 0.8397197372881406,
 0.8657778044379111,
 0.7923453329598654,
 0.9123065098233409,
 0.7696782548089086,
 0.8763096528743606,
 0.850863436649046,
 0.8365710281901951,
 0.9263020709610754,
 1.094825499843248,
 0.8413303037396078,
 0.9528862156557405,
 0.9393900572112739,
 0.9868070909401871,
 0.7598325734695252,
 0.7893871169574536,
 0.9645020126048776,
 0.8973887731715806,
 0.8734195671789149,
 0.9962355285840295,
 0.9359022900060494,
 0.8659732907907493,
 0.7132506036524863,
 0.9493593558481184,
 0.7100366014693524,
 0.6977171481815825,
 0.9434613517622082,
 0.8786333921538945,
 0.7785560344648665,
 0.9202940403206842,
 0.8200890986714613,
 0.9275260549930315,
 0.9586426557958916,
 0.9385156822652083,
 0.8545904366187753,
 0.9367249137177883,
 0.8604613441321729,
 0.8744167103069724,
 0.9313853896560672,
 0.8724160691104835,
 0.862376469867286,
 0.9550797134719545,
 0.8216135931520181,
 0.8638195101207606,
 0.6996588900626184,
 0.756259934362276,
 0.8784544700757855,
 0.7175997946831568,
 0.7879829863683665,
 0.7139842354807344,
 0.6152742556514186,
 0.869753592325729,
 0.9243008302695327,
 0.8951441140224483,
 0.7310606843265501,
 0.8674630671555144,
 0.8747854723004664,
 0.796579337221507,
 0.6767733251283661,
 1.0,
 0.908892498227496,
 1.0,
 0.972736499225375,
 0.9626536011133531,
 1.0768553971684895,
 0.9207494150500037,
 1.1474342145909446,
 0.8666167653140987,
 0.7474717159025857,
 0.8349945077262587,
 0.9190644827324265,
 0.9645020126048776,
 1.2661778628259441,
 1.0,
 0.9680508712249127,
 0.6812275472707334,
 0.8514495191657997,
 0.9106119520303981,
 0.9544716175540365,
 0.8334987971726835,
 0.807140564500886,
 0.9884203006828278,
 0.7012954690287844,
 0.8774456108717855,
 0.9762213786686116,
 0.9531352490856196,
 1.0204947725782638,
 0.8852488239138027,
 0.9590104548434722,
 0.916861570473845,
 0.5893522928860987,
 0.8662154236073252,
 0.9402200685178059,
 0.878634493130587,
 0.9576661797973736,
 0.8820522859034228,
 1.0,
 0.9932430735776027,
 0.8565423527530998,
 0.9213019467809941,
 0.8522627096162732,
 0.9366469791454121,
 0.9689524462716178,
 0.9809843234922522,
 1.0,
 0.9923831777569547,
 0.9409854462386107,
 0.9220412199422763,
 0.8387917269672405,
 0.8617828956737816,
 0.8092361324419614,
 0.9468101662069506,
 0.9387925300234868,
 0.8335375085661632,
 0.977209360796623,
 0.9052797722894625,
 0.868481548906266,
 1.0882956239879296,
 0.9717401253661191,
 0.9897526137108681,
 0.9725654305890807,
 0.8976552700312493,
 1.0,
 0.7087302876209173,
 0.9292855772335497,
 0.7572432563197687,
 0.8043235929862158,
 1.0,
 0.8015042780664451,
 0.6660363778638222,
 1.0330303167720853,
 0.858121732097198,
 0.7888177893725862,
 0.9026597624238326,
 0.7401055714677278,
 0.8130414325921564,
 0.8911575687638443,
 0.8014371892059118,
 0.7114705705036704,
 0.8868369036040683,
 0.9238696892818334,
 0.8626670364084438,
 0.9715658436795285,
 0.9863787943610597,
 0.9774217499874337,
 0.8962371070298417,
 0.8427756921648735,
 0.7614019112918848,
 1.1499492542604375,
 1.1207485915849493,
 0.8045103152215188,
 0.8741480909365994,
 1.0656152875182778,
 0.8659182450449171,
 0.9455005460328275,
 0.7424032139897299,
 0.9887776589992181,
 0.9230787958416278,
 0.6408717525758331,
 0.9332566035216656,
 0.8572493847149107,
 0.7668248103027885,
 0.9480941655947918,
 0.7309200630953285,
 0.914747439066805,
 0.8001449612402931,
 0.9895068381111036,
 1.0842329964230049,
 1.0775800843106191,
 0.9693633320596617,
 0.7350226720766615,
 0.7255996570450796,
 1.0648101614744754,
 0.6634161115757886,
 0.9328682657815051,
 0.779235549217771,
 0.8598022385761677,
 0.8943568577992487,
 0.8706226542648553,
 0.7954448914720833,
 0.7645315828148522,
 0.9325082894883612,
 0.6510040986028923,
 0.7221354965314486,
 0.9629463382965459,
 0.8661791611546245,
 0.8109673326216705,
 1.0,
 0.987118078420174,
 0.8861388209251249,
 0.8493988774741794,
 0.9623880901194091,
 0.9919981356685027,
 0.799672943856905,
 0.8909426353358639,
 0.951237370795559,
 0.9161496492979615,
 0.929597071170372,
 1.237037785616205,
 1.0,
 0.7186196350925852,
 0.6983370848213111,
 0.9198221360575831,
 0.9131739722746153,
 0.9576885387955744,
 1.0,
 0.8615183426658927,
 0.7684279922533094,
 1.0,
 0.9731024561395404,
 0.9090411225602284,
 1.0,
 0.7588684467110766,
 0.8119742078269092,
 0.9907325357000829,
 0.9897526137108681,
 0.8478777714270107,
 0.9198570378610859,
 1.0,
 0.9475929990506136,
 0.7764839494723416,
 0.9001313908927803,
 0.9579953078864982,
 0.9378469509826688,
 0.8639796815386723,
 0.9094069237393249,
 0.883944676977249,
 0.8869063637821233,
 0.9649203470220212,
 1.066410653376284,
 0.9067838187316292,
 1.1422783179115756,
 0.9327780304637681,
 0.950170863395711,
 0.8041448244502439,
 0.8602302951655826,
 0.9428295884533956,
 0.9785577797306672,
 0.9035885906942519,
 0.813350552837262,
 0.9881261151497318,
 0.8357581932562912,
 0.9903844699644316,
 0.9682310646665028,
 0.795057429792213,
 0.9558550669573477,
 0.7373852089076878,
 0.8619517109836878,
 0.6780196526766916,
 0.8400265508461137,
 0.8798573996580815,
 0.9847663555139095,
 1.0,
 0.9310373879341445,
 0.9780905151310961,
 0.9669459586645461,
 0.9071468288223411,
 1.0228227432165813,
 0.9358323992169648,
 0.9187634456613913,
 0.9842503149068834,
 0.9685006298137669,
 0.8291203107572664,
 0.9043745611042991,
 1.0459450613385752,
 0.7815205383877941,
 0.9850957535545045,
 0.906842788653383,
 0.9246327183886237,
 0.9773816108446135,
 0.9554201780320442,
 0.8978692620620149,
 0.9323834816208051,
 0.8451762506786085,
 0.9783568275647537,
 0.9000535537631773,
 1.0614843177347917,
 0.6971165290447686,
 1.0028421135926886,
 1.0030674748490742,
 0.7709738920359949,
 0.7554678432742165,
 0.9770230239860549,
 0.9453282894893179,
 0.8828180934411415,
 0.9716192637181654,
 0.7433206464267763,
 0.9191143300970029,
 0.9519169588658118,
 0.9495160465607092,
 0.8921298757972618,
 0.8173689342393122,
 0.8939273690534418,
 0.9155392619473561,
 0.8917853931378403,
 0.8789168527462726,
 0.961828879803821,
 0.963400176493869,
 0.7941650144859203,
 0.8162373779737151,
 0.8618243101373841,
 0.8821627637820944,
 1.0,
 0.9218467257827192,
 1.3199394907020057,
 0.9645689268724713,
 0.8806366280804316,
 0.7248731275538077,
 1.0650796435577246,
 0.8143190133213128,
 0.9478854654248206,
 1.3537946289930896,
 1.1226496853523018,
 0.7318282454253038,
 0.9456614160248558,
 0.8320650560517774,
 0.7427667216185982,
 0.9142271757262596,
 0.8832564753680309,
 0.8904343746275625,
 0.888369616259923,
 0.8425655741988666,
 0.9191248288459095,
 0.7749018802950712,
 0.6883913880884338,
 0.7749034051774868,
 1.0469594233453998,
 1.2865949793991354,
 0.8260160177438599,
 0.8997646936894176,
 0.7017810090347236,
 0.9069031614132046,
 0.7451086808781127,
 0.7347669988361292,
 0.923021184324937,
 0.811730281091918,
 0.9565240219931005,
 0.8954910336000816,
 0.9254119850567325,
 0.9491695564215074,
 1.146421727699133,
 0.7565683397810954,
 0.8969306112260198,
 0.8343192194123414,
 0.8481843669839136,
 0.6783591774992226,
 1.0,
 1.0354979873951224,
 0.9229237271833417,
 0.9362035185673662,
 0.7598270743193285,
 1.010742179662929,
 0.9179515957741609,
 0.865185233651821,
 0.8463762810688842,
 0.92528448675505,
 0.9503548549120364,
 0.9870312347643193,
 1.0,
 0.9733180787723618,
 1.0062440741935188,
 1.0,
 0.9967076405047355,
 0.7532932178337699,
 0.715535900340357,
 0.813995254053795,
 0.8302572297914768,
 0.8966917912171208,
 0.9487630685543402,
 0.9277614152637174,
 0.9328720941000576,
 0.7190220929183097,
 1.0409895451565279,
 0.9690384741639626,
 0.7373340700547489,
 1.0041931956661332,
 0.9758838664684891,
 1.0,
 0.8670159899113696,
 0.8606413633999465,
 0.7792152585318953,
 0.9307604794704933,

In [37]:
len(score)

73340

In [39]:
type(score)

list

In [40]:
score.pop(4)

0

In [41]:
score

[1.0663423124373064,
 1.0081171394848936,
 0.7752643031454982,
 1.1793651366751645,
 1.0710171014012735,
 0.7208359085415273,
 0.9496816520064016,
 0.9692578411326042,
 1.006271298563887,
 0.9136201692776561,
 0.9212054478980346,
 1.2668064634551697,
 0.8283724243872302,
 1.0,
 0.9732170105270752,
 0.667644787441699,
 0.9507532527287035,
 0.8835500754803396,
 0.98775902358261,
 0.8022473248351534,
 0.965080318795035,
 0.8558041466095413,
 0.9302888827122032,
 0.8867106954142622,
 1.0454040187964675,
 0.8392542832961136,
 0.902472808084771,
 0.7471353233566108,
 0.9074679954931069,
 0.8556216596325039,
 0.944696098782017,
 0.9103073205728243,
 0.9456505548381843,
 1.0596702204087756,
 1.000970455608218,
 0.8900170154593897,
 0.7314840081605104,
 0.9262329838633723,
 0.8962954486462924,
 0.8067767266264004,
 0.9851748145481759,
 0.7585054324734527,
 0.8201734485172012,
 0.9905775870646253,
 0.7002043563275343,
 0.8996876355078542,
 0.891369453002009,
 1.0167339117370437,
 0.7715056962052254,
 0.8597104166811484,
 0.847666227946847,
 0.9231978874197193,
 1.2918738422168554,
 0.8691829066295853,
 0.8882908898433832,
 0.9447303415522683,
 0.9621649685986069,
 1.0,
 0.9526693501398367,
 0.95045204949818,
 0.8328312836702803,
 1.0,
 0.9542185159229583,
 0.9558936886777952,
 0.9534858819234754,
 0.9577188291455262,
 0.9074369446646527,
 0.9521405588538392,
 0.9077735233978125,
 0.888271302605841,
 0.9093005653535811,
 0.7718308414083965,
 1.0,
 0.8632689020632128,
 1.0,
 0.7755187172889995,
 0.9428738331771607,
 0.8455183585874518,
 0.7742228922538699,
 0.8027043195403849,
 0.8858875297771713,
 1.0,
 0.9251500055518552,
 0.921098917459283,
 1.007137571322094,
 0.8160294271892696,
 0.884605255436426,
 1.1004034704222627,
 0.9962336927041759,
 0.9618598893642571,
 0.9569501765344746,
 0.7510007739866462,
 0.8886916841621422,
 0.8409553340532973,
 0.9574923235413786,
 0.9079327818081289,
 0.9047420298356783,
 0.7897210993777275,
 0.9355207976906179,
 0.9347860329896507,
 0.8589637079359119,
 0.9304631184583443,
 0.8985765632041127,
 0.946654236336455,
 0.8297157586622553,
 0.9210387044907318,
 0.834771601846791,
 0.9009362993016944,
 0.898942959213102,
 0.9258566357445528,
 0.9393345597008568,
 1.0,
 1.0,
 0.9300218236450896,
 0.9610658065021451,
 0.9129017665205831,
 0.9190834101967177,
 1.0,
 0.7911912009355203,
 0.8797234486754848,
 0.8386015641223559,
 0.72812868722797,
 0.9203674079242683,
 0.9044445152397765,
 0.8695166145850531,
 0.8345694809708178,
 0.8628459196580721,
 0.7152819936417318,
 0.8207798312697013,
 1.0,
 0.8667896222306569,
 1.1188343398855254,
 0.8972146167062134,
 0.9170893291152051,
 0.987109384404485,
 0.988819184917762,
 0.965599346848559,
 0.7865582527788283,
 0.8947749957116113,
 0.8012798904887369,
 0.9548073026611305,
 1.0124479795680603,
 0.8793849910443432,
 1.1199446126732602,
 0.8697585349389586,
 0.8841222321576836,
 0.6225527886204192,
 0.9824006355253991,
 0.9570312813482835,
 1.060797320555316,
 0.808662138450284,
 0.9032173725195213,
 0.982700420860256,
 0.7997993932741823,
 0.9162727580547854,
 1.070044631233338,
 0.904885698046674,
 0.8790825974992588,
 0.8490396488559802,
 0.9475341905555182,
 0.7837931689029702,
 0.8791960713768147,
 0.8653955776752932,
 0.8474765900847642,
 0.919465781027103,
 0.9531937782496844,
 0.8095154771324322,
 0.8234413372738263,
 0.7655319429931488,
 1.0874874591166825,
 0.8084944226921154,
 0.8574145517446415,
 0.9517901534811234,
 0.9747492442794683,
 0.7857179592120438,
 0.9260492304680734,
 0.9588538010777333,
 0.94967310128334,
 0.9366169710164515,
 1.0333630725959422,
 0.7826062530491348,
 0.8873988482749537,
 0.9314357598029123,
 0.8722296114244469,
 0.8833299670676332,
 1.1018793976314933,
 0.7487691107133989,
 0.8521083970341002,
 0.771207583469818,
 0.9139302746909191,
 0.9423197133365112,
 0.9264608057628623,
 0.9385156822652083,
 0.9366776484091173,
 0.9172448901779856,
 1.1075417143803454,
 0.9645931140947537,
 0.9059904401549853,
 0.903632119254615,
 0.760324685660082,
 0.9929788991735985,
 0.9196681418712332,
 0.9522093718889205,
 1.0,
 0.9167993202798417,
 0.8725229300371825,
 0.9160999462260473,
 0.6835916902041759,
 0.8637211408506711,
 1.0,
 0.9299734428742766,
 0.8444607860330053,
 0.9380787835581388,
 0.9165721918358788,
 0.8837688153253255,
 0.9835215828349658,
 0.8670192731351596,
 0.9423082881038225,
 1.0347949873407272,
 0.8565531641712159,
 1.0,
 0.9212057718598701,
 0.8935385783708051,
 0.6846438255067127,
 0.9721401431142614,
 0.7999991029116591,
 0.963250734782728,
 0.8937584812285224,
 0.8241977586071046,
 0.9738035331401177,
 0.7928630502508712,
 0.8461510379110839,
 0.6888847157264473,
 0.8890596211019128,
 1.0232388877509624,
 1.0,
 0.9548913031042199,
 1.1703355817025027,
 0.8801171506687824,
 0.8208506073172783,
 0.9446034806207642,
 0.7056695629514542,
 0.7469078102020337,
 0.9081438654380608,
 0.9067085783436335,
 0.7291799730404317,
 0.8624331408603215,
 0.6907349442967526,
 0.9259169653830547,
 0.7955496687706052,
 0.8243294543912725,
 0.9491749175762626,
 0.9133738932568632,
 0.7411975362088374,
 0.9713423878860492,
 0.9280108847277192,
 0.9954456060937191,
 0.883683890009086,
 0.7747214926260885,
 0.8583829820037642,
 0.8394934911865063,
 0.9472529162864403,
 0.9533264479618624,
 0.9357315959691159,
 1.0312882434605577,
 0.8728169272667776,
 0.8302475119168526,
 1.0606664936803072,
 0.7146963178904044,
 0.8387587393567848,
 0.7842115864662016,
 1.2090640995762174,
 0.8934824414361875,
 0.8752405409134182,
 0.9346194052763853,
 0.9291738045873894,
 0.9370600863634302,
 0.8266756193028346,
 0.8809405709830721,
 0.7031311996547931,
 0.9727575887221195,
 0.9029180502814486,
 1.2736598460687498,
 0.9365520581514912,
 1.0025132302643063,
 0.8156977119330739,
 1.0685514240945664,
 0.8999758035672294,
 0.8951505843781776,
 0.886055294259193,
 0.7527071711757976,
 0.7224081444917192,
 0.8604897790457471,
 0.7514937761484622,
 0.88932166387969,
 0.7814729785701021,
 0.9631914240751124,
 0.8155000923456819,
 0.8104685622075252,
 1.060033793356653,
 0.8244854236736225,
 0.9875003872312339,
 0.9652135369910907,
 0.924815363158651,
 0.9662975054729528,
 0.870866966546785,
 0.8717152115788754,
 1.037935713886193,
 0.9381873077459969,
 0.8694798925929983,
 0.9927540036655167,
 0.9077221826674875,
 0.8866438329551889,
 0.9118314665243697,
 0.768911350214579,
 0.9438646900594584,
 0.9391074604034803,
 0.73862151041286,
 0.7145341077760117,
 0.8031509751991364,
 0.9223884528167421,
 0.8911424729953279,
 0.8864589895071013,
 0.747459066319154,
 1.0017259712098607,
 1.0454738174830178,
 0.9078997746227802,
 0.9735384522495604,
 0.908908639794797,
 0.788294331337591,
 0.9858531042802742,
 0.9060683211125712,
 0.8873617998180119,
 0.8399778361573313,
 0.9390596168274112,
 1.0580543969205098,
 0.8934907673751337,
 0.9168939896302813,
 0.7318157270203376,
 0.9180394125052387,
 0.8720767380228155,
 0.9297862419435242,
 0.8177272182342684,
 0.9672991840705623,
 1.0,
 0.8352654445343117,
 0.7561396283591174,
 0.7802397144441746,
 1.0,
 0.7267152784753919,
 0.8876182583170087,
 0.7911153999517982,
 1.0,
 0.9572769097156464,
 0.8612712747029034,
 0.9007253878976437,
 0.8728369660975478,
 0.9758645503792638,
 0.8181604921714538,
 1.0,
 0.7568802913969854,
 0.8673360464320014,
 0.9247550908621844,
 0.9865355145715279,
 0.8690686424016095,
 0.9307247821579206,
 0.8748006648924179,
 0.8634044329732575,
 0.828304222594999,
 1.2673017303709888,
 0.800115923325294,
 1.0009953141428747,
 0.8880899135948698,
 0.9068951760016011,
 0.9816770598527265,
 1.0,
 0.7265860016415627,
 0.9352891527937108,
 1.2072515771731829,
 0.8609052381907598,
 0.8912087434265319,
 0.8787142790917453,
 0.7930987053335795,
 0.926340756770885,
 0.7718359820419542,
 0.9897526137108681,
 0.8981003942164419,
 0.8491515308548486,
 0.9674977747926512,
 0.6130547945973153,
 0.8309393728185192,
 0.962507766905006,
 0.7487589668118182,
 1.1250169406990846,
 0.9219861373359806,
 1.0752497317650211,
 1.041414318627643,
 0.7723117946137912,
 0.850164008222565,
 1.0,
 0.9071420915364944,
 0.8587385544579516,
 0.8023901594637666,
 0.9286811505413861,
 1.3079774733908636,
 0.9763109160227865,
 0.862906588834586,
 0.9124315544639974,
 0.965078668011599,
 0.9542797736647552,
 0.9845610770582693,
 0.9941078665426347,
 0.9253123223250095,
 0.767859686996855,
 0.8035798622942885,
 0.7724220447127167,
 0.8463478125233548,
 0.8387389839468025,
 0.8021411242086757,
 0.9639871892772836,
 0.8741226913489535,
 0.9561681714281217,
 0.8963193501012889,
 0.9646585229277044,
 0.7699998569293385,
 0.7020176167399432,
 0.9826229379205614,
 0.9350164112616604,
 0.9372130769523513,
 0.8973876076562426,
 0.8189378446868684,
 0.9013501900968265,
 0.8529625198727677,
 0.8990782342422527,
 1.0803322836795417,
 0.7155083957132917,
 0.8527484053401221,
 0.9541479109648646,
 0.8509083319686583,
 0.9729666641248086,
 0.940959385703701,
 0.8059431606671204,
 0.8004348356603376,
 0.7298322477271885,
 0.8962853569153298,
 0.9225187556191154,
 0.9087839743808436,
 0.9864958451245509,
 0.9375128156753936,
 1.0723098907708672,
 0.9560314127411159,
 0.9724797466755495,
 0.804865652305331,
 0.8943506549296585,
 1.0,
 0.9437200763693626,
 0.8096452330415717,
 0.7229762955752134,
 0.7693545737900086,
 0.7977030596603549,
 0.8264263499099792,
 1.0,
 0.9355665669806202,
 0.9039524641035599,
 1.1266094883759368,
 0.9545182036499993,
 0.8354109688680308,
 0.9567486046280524,
 0.9469150198093986,
 1.0,
 0.9505687911562897,
 0.9782620109965502,
 0.8878871508693242,
 1.0648837675873222,
 1.2565929178039548,
 0.6704913480696721,
 0.9050863132261852,
 0.9910076427848552,
 0.9251964281127651,
 0.8296628819353257,
 0.936976044965768,
 0.9613248571424603,
 0.8173211848514708,
 0.9431121996873038,
 0.9087310450324699,
 0.8791207314782721,
 0.7906978013376056,
 0.8884530149540479,
 0.9897526137108681,
 0.6815006220870328,
 1.1656572745105716,
 0.721323099198558,
 0.8590425492000126,
 0.86186755506508,
 0.7451422276026549,
 1.030897032184439,
 1.0,
 0.7445736303907386,
 0.7766330761325224,
 0.9239214641620849,
 0.8810911520587301,
 1.0636449936549166,
 0.8902596801316403,
 1.0896646300299047,
 0.8048033016530938,
 0.816354510850646,
 0.9692578411326042,
 0.8501108689468417,
 0.7830340537911618,
 0.9586310610483316,
 0.8952085035356805,
 0.805653510300776,
 0.995816522065739,
 0.8509305425774676,
 0.9167304084012666,
 0.9047773478128669,
 0.7880487532006166,
 0.9589727632997321,
 0.9152611052237852,
 0.9600971103350998,
 0.9791468728144221,
 1.1607558724107574,
 0.7927757507991424,
 0.9509778599405525,
 0.953365510770377,
 0.6817370871269333,
 0.7668585950010229,
 0.8503601338982402,
 1.099028616571271,
 0.8414390401156149,
 0.8513488771162777,
 0.9300978709634532,
 1.0,
 1.1542441344937886,
 0.8644957222991082,
 0.9353458198863893,
 0.6577060759582545,
 0.7496980831414373,
 0.8706191775204088,
 0.915160102679627,
 0.9307278626891277,
 0.8555210515342194,
 0.9500535364819651,
 0.7009119028031505,
 0.7625096777836559,
 0.9692578411326042,
 0.9771495332708643,
 0.7250060385686017,
 0.9501849384501992,
 0.7603623005385627,
 0.9880787021204879,
 0.9692578411326042,
 0.8260362290006753,
 0.9460286648838901,
 0.9212370377052994,
 0.7468762441139392,
 0.9442570100765902,
 0.8195214649873246,
 0.7782235189993761,
 0.7677637281697328,
 0.8223377291635341,
 0.7936281803199745,
 0.817712733327632,
 0.6537384902748482,
 0.8612748229760392,
 0.9666674493719438,
 0.859272573074779,
 0.8195094112321641,
 0.8097862342878984,
 0.7040899690453928,
 1.2327539702135024,
 1.0,
 0.8804662350163734,
 0.9465895081430754,
 0.7144135330553653,
 0.885695306904847,
 0.8621297785041712,
 0.8130334457523762,
 0.9515417201973618,
 1.0,
 1.0014109183306308,
 0.7513812152622924,
 0.9602810009612832,
 0.9130848236479923,
 0.9005161233151606,
 1.1693810457069644,
 0.8870826571900023,
 0.9431261122642935,
 0.8775385038364976,
 0.6764234133213385,
 0.9282682959760763,
 0.8134345386642163,
 0.9318423871839632,
 1.0312632495195746,
 0.728933524043001,
 0.7721762856408383,
 0.9484787795817216,
 0.948904004015029,
 0.9384701551817878,
 0.9555476885546574,
 0.8224684665297468,
 0.9226647011570699,
 0.8203475729098778,
 0.9549482622578386,
 0.8991230301979126,
 0.9270200991837435,
 0.8870264322930217,
 0.7795591353192796,
 0.8397197372881406,
 0.8657778044379111,
 0.7923453329598654,
 0.9123065098233409,
 0.7696782548089086,
 0.8763096528743606,
 0.850863436649046,
 0.8365710281901951,
 0.9263020709610754,
 1.094825499843248,
 0.8413303037396078,
 0.9528862156557405,
 0.9393900572112739,
 0.9868070909401871,
 0.7598325734695252,
 0.7893871169574536,
 0.9645020126048776,
 0.8973887731715806,
 0.8734195671789149,
 0.9962355285840295,
 0.9359022900060494,
 0.8659732907907493,
 0.7132506036524863,
 0.9493593558481184,
 0.7100366014693524,
 0.6977171481815825,
 0.9434613517622082,
 0.8786333921538945,
 0.7785560344648665,
 0.9202940403206842,
 0.8200890986714613,
 0.9275260549930315,
 0.9586426557958916,
 0.9385156822652083,
 0.8545904366187753,
 0.9367249137177883,
 0.8604613441321729,
 0.8744167103069724,
 0.9313853896560672,
 0.8724160691104835,
 0.862376469867286,
 0.9550797134719545,
 0.8216135931520181,
 0.8638195101207606,
 0.6996588900626184,
 0.756259934362276,
 0.8784544700757855,
 0.7175997946831568,
 0.7879829863683665,
 0.7139842354807344,
 0.6152742556514186,
 0.869753592325729,
 0.9243008302695327,
 0.8951441140224483,
 0.7310606843265501,
 0.8674630671555144,
 0.8747854723004664,
 0.796579337221507,
 0.6767733251283661,
 1.0,
 0.908892498227496,
 1.0,
 0.972736499225375,
 0.9626536011133531,
 1.0768553971684895,
 0.9207494150500037,
 1.1474342145909446,
 0.8666167653140987,
 0.7474717159025857,
 0.8349945077262587,
 0.9190644827324265,
 0.9645020126048776,
 1.2661778628259441,
 1.0,
 0.9680508712249127,
 0.6812275472707334,
 0.8514495191657997,
 0.9106119520303981,
 0.9544716175540365,
 0.8334987971726835,
 0.807140564500886,
 0.9884203006828278,
 0.7012954690287844,
 0.8774456108717855,
 0.9762213786686116,
 0.9531352490856196,
 1.0204947725782638,
 0.8852488239138027,
 0.9590104548434722,
 0.916861570473845,
 0.5893522928860987,
 0.8662154236073252,
 0.9402200685178059,
 0.878634493130587,
 0.9576661797973736,
 0.8820522859034228,
 1.0,
 0.9932430735776027,
 0.8565423527530998,
 0.9213019467809941,
 0.8522627096162732,
 0.9366469791454121,
 0.9689524462716178,
 0.9809843234922522,
 1.0,
 0.9923831777569547,
 0.9409854462386107,
 0.9220412199422763,
 0.8387917269672405,
 0.8617828956737816,
 0.8092361324419614,
 0.9468101662069506,
 0.9387925300234868,
 0.8335375085661632,
 0.977209360796623,
 0.9052797722894625,
 0.868481548906266,
 1.0882956239879296,
 0.9717401253661191,
 0.9897526137108681,
 0.9725654305890807,
 0.8976552700312493,
 1.0,
 0.7087302876209173,
 0.9292855772335497,
 0.7572432563197687,
 0.8043235929862158,
 1.0,
 0.8015042780664451,
 0.6660363778638222,
 1.0330303167720853,
 0.858121732097198,
 0.7888177893725862,
 0.9026597624238326,
 0.7401055714677278,
 0.8130414325921564,
 0.8911575687638443,
 0.8014371892059118,
 0.7114705705036704,
 0.8868369036040683,
 0.9238696892818334,
 0.8626670364084438,
 0.9715658436795285,
 0.9863787943610597,
 0.9774217499874337,
 0.8962371070298417,
 0.8427756921648735,
 0.7614019112918848,
 1.1499492542604375,
 1.1207485915849493,
 0.8045103152215188,
 0.8741480909365994,
 1.0656152875182778,
 0.8659182450449171,
 0.9455005460328275,
 0.7424032139897299,
 0.9887776589992181,
 0.9230787958416278,
 0.6408717525758331,
 0.9332566035216656,
 0.8572493847149107,
 0.7668248103027885,
 0.9480941655947918,
 0.7309200630953285,
 0.914747439066805,
 0.8001449612402931,
 0.9895068381111036,
 1.0842329964230049,
 1.0775800843106191,
 0.9693633320596617,
 0.7350226720766615,
 0.7255996570450796,
 1.0648101614744754,
 0.6634161115757886,
 0.9328682657815051,
 0.779235549217771,
 0.8598022385761677,
 0.8943568577992487,
 0.8706226542648553,
 0.7954448914720833,
 0.7645315828148522,
 0.9325082894883612,
 0.6510040986028923,
 0.7221354965314486,
 0.9629463382965459,
 0.8661791611546245,
 0.8109673326216705,
 1.0,
 0.987118078420174,
 0.8861388209251249,
 0.8493988774741794,
 0.9623880901194091,
 0.9919981356685027,
 0.799672943856905,
 0.8909426353358639,
 0.951237370795559,
 0.9161496492979615,
 0.929597071170372,
 1.237037785616205,
 1.0,
 0.7186196350925852,
 0.6983370848213111,
 0.9198221360575831,
 0.9131739722746153,
 0.9576885387955744,
 1.0,
 0.8615183426658927,
 0.7684279922533094,
 1.0,
 0.9731024561395404,
 0.9090411225602284,
 1.0,
 0.7588684467110766,
 0.8119742078269092,
 0.9907325357000829,
 0.9897526137108681,
 0.8478777714270107,
 0.9198570378610859,
 1.0,
 0.9475929990506136,
 0.7764839494723416,
 0.9001313908927803,
 0.9579953078864982,
 0.9378469509826688,
 0.8639796815386723,
 0.9094069237393249,
 0.883944676977249,
 0.8869063637821233,
 0.9649203470220212,
 1.066410653376284,
 0.9067838187316292,
 1.1422783179115756,
 0.9327780304637681,
 0.950170863395711,
 0.8041448244502439,
 0.8602302951655826,
 0.9428295884533956,
 0.9785577797306672,
 0.9035885906942519,
 0.813350552837262,
 0.9881261151497318,
 0.8357581932562912,
 0.9903844699644316,
 0.9682310646665028,
 0.795057429792213,
 0.9558550669573477,
 0.7373852089076878,
 0.8619517109836878,
 0.6780196526766916,
 0.8400265508461137,
 0.8798573996580815,
 0.9847663555139095,
 1.0,
 0.9310373879341445,
 0.9780905151310961,
 0.9669459586645461,
 0.9071468288223411,
 1.0228227432165813,
 0.9358323992169648,
 0.9187634456613913,
 0.9842503149068834,
 0.9685006298137669,
 0.8291203107572664,
 0.9043745611042991,
 1.0459450613385752,
 0.7815205383877941,
 0.9850957535545045,
 0.906842788653383,
 0.9246327183886237,
 0.9773816108446135,
 0.9554201780320442,
 0.8978692620620149,
 0.9323834816208051,
 0.8451762506786085,
 0.9783568275647537,
 0.9000535537631773,
 1.0614843177347917,
 0.6971165290447686,
 1.0028421135926886,
 1.0030674748490742,
 0.7709738920359949,
 0.7554678432742165,
 0.9770230239860549,
 0.9453282894893179,
 0.8828180934411415,
 0.9716192637181654,
 0.7433206464267763,
 0.9191143300970029,
 0.9519169588658118,
 0.9495160465607092,
 0.8921298757972618,
 0.8173689342393122,
 0.8939273690534418,
 0.9155392619473561,
 0.8917853931378403,
 0.8789168527462726,
 0.961828879803821,
 0.963400176493869,
 0.7941650144859203,
 0.8162373779737151,
 0.8618243101373841,
 0.8821627637820944,
 1.0,
 0.9218467257827192,
 1.3199394907020057,
 0.9645689268724713,
 0.8806366280804316,
 0.7248731275538077,
 1.0650796435577246,
 0.8143190133213128,
 0.9478854654248206,
 1.3537946289930896,
 1.1226496853523018,
 0.7318282454253038,
 0.9456614160248558,
 0.8320650560517774,
 0.7427667216185982,
 0.9142271757262596,
 0.8832564753680309,
 0.8904343746275625,
 0.888369616259923,
 0.8425655741988666,
 0.9191248288459095,
 0.7749018802950712,
 0.6883913880884338,
 0.7749034051774868,
 1.0469594233453998,
 1.2865949793991354,
 0.8260160177438599,
 0.8997646936894176,
 0.7017810090347236,
 0.9069031614132046,
 0.7451086808781127,
 0.7347669988361292,
 0.923021184324937,
 0.811730281091918,
 0.9565240219931005,
 0.8954910336000816,
 0.9254119850567325,
 0.9491695564215074,
 1.146421727699133,
 0.7565683397810954,
 0.8969306112260198,
 0.8343192194123414,
 0.8481843669839136,
 0.6783591774992226,
 1.0,
 1.0354979873951224,
 0.9229237271833417,
 0.9362035185673662,
 0.7598270743193285,
 1.010742179662929,
 0.9179515957741609,
 0.865185233651821,
 0.8463762810688842,
 0.92528448675505,
 0.9503548549120364,
 0.9870312347643193,
 1.0,
 0.9733180787723618,
 1.0062440741935188,
 1.0,
 0.9967076405047355,
 0.7532932178337699,
 0.715535900340357,
 0.813995254053795,
 0.8302572297914768,
 0.8966917912171208,
 0.9487630685543402,
 0.9277614152637174,
 0.9328720941000576,
 0.7190220929183097,
 1.0409895451565279,
 0.9690384741639626,
 0.7373340700547489,
 1.0041931956661332,
 0.9758838664684891,
 1.0,
 0.8670159899113696,
 0.8606413633999465,
 0.7792152585318953,
 0.9307604794704933,

In [42]:
min(score)

0.5297075410026849

In [53]:
len(score)

73339

In [43]:
most_similar_user = score.index(min(score))

In [44]:
most_similar_user

60042

In [45]:
common_movie.iloc[60042]

        anime_id
rating  1           6.0
        5           6.0
        6           9.0
        7           0.0
        15          0.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 60184, Length: 1720, dtype: float64

In [46]:
common_movie_reset = common_movie.reset_index()

In [47]:
common_movie_reset

         user_id rating                                            ...
anime_id              1     5     6    7   15   16   18   19   20  ... 32379
0              1    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0 -1.0  ...   0.0  \
1              2    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0
2              3    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  8.0  ...   0.0
3              4    0.0   0.0  -1.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0
4              5    0.0   0.0   8.0  0.0  6.0  0.0  6.0  0.0  6.0  ...   0.0
...          ...    ...   ...   ...  ...  ...  ...  ...  ...  ...  ...   ...
73335      73512    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0
73336      73513    9.0   8.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0
73337      73514    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0
73338      73515   10.0  10.0  10.0  0.0  0.0  0.0  0.0  9.0  0.0  ...   0.0
73339      73516    0.0   0.0   0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0


anime_id 32380 32438 32542 32729 32828 32935 32998 33028 34240
0          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4          0.0   0.0   0.0   0.0   7.0   0.0   0.0   0.0   0.0
...        ...   ...   ...   ...   ...   ...   ...   ...   ...
73335      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73336      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73337      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73338      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
73339      0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[73340 rows x 1721 columns]

In [54]:
common_movie_reset.iloc[60043] #since we dropped the user we were taking as reference

         anime_id
user_id              60185.0
rating   1               8.0
         5               0.0
         6               7.0
         7               0.0
                      ...
         32828           0.0
         32935           0.0
         32998           0.0
         33028           0.0
         34240           0.0
Name: 60043, Length: 1721, dtype: float64

In [55]:
common_movie.iloc[60043]

        anime_id
rating  1           8.0
        5           0.0
        6           7.0
        7           0.0
        15          8.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 60185, Length: 1720, dtype: float64

In [60]:
# # Replace 'row_index' with the index of the row you're interested in
# row_index = 5  # Change this to your desired row index

# # Select the row using .loc[] and then filter for non-zero values
# non_zero_values = common_movie.loc[row_index][common_movie.loc[row_index] != 0]

In [61]:
non_zero_values

        anime_id
rating  6           8.0
        15          6.0
        18          6.0
        20          6.0
        22          5.0
                   ...
        31240       8.0
        31636      -1.0
        31964      -1.0
        32182       9.0
        32828       7.0
Name: 5, Length: 400, dtype: float64

In [62]:
my_ratings

array([0., 0., 8., ..., 0., 0., 0.])

In [68]:
row_index = 60043  # Change this to your desired row index

# Select the row using .loc[] and then filter for non-zero values
non_zero_values = common_movie.iloc[row_index][common_movie.iloc[row_index] != 0]

In [75]:
non_zero_values

        anime_id
rating  1           8.0
        6           7.0
        15          8.0
        16          6.0
        18          8.0
                   ...
        31764       7.0
        31964       8.0
        32093       8.0
        32182       9.0
        32282       9.0
Name: 60185, Length: 449, dtype: float64

In [73]:
common_movie.loc[3]

        anime_id
rating  1           0.0
        5           0.0
        6           0.0
        7           0.0
        15          0.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 3, Length: 1720, dtype: float64

In [74]:
common_movie.iloc[3]

        anime_id
rating  1           0.0
        5           0.0
        6          -1.0
        7           0.0
        15          0.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 4, Length: 1720, dtype: float64

In [66]:
common_movie.loc[60043]

        anime_id
rating  1           0.0
        5           0.0
        6           0.0
        7           0.0
        15          0.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 60043, Length: 1720, dtype: float64

In [67]:
common_movie.iloc[60043]

        anime_id
rating  1           8.0
        5           0.0
        6           7.0
        7           0.0
        15          8.0
                   ...
        32828       0.0
        32935       0.0
        32998       0.0
        33028       0.0
        34240       0.0
Name: 60185, Length: 1720, dtype: float64

In [86]:
recm = pd.DataFrame(non_zero_values)
recm

                 60185
       anime_id
rating 1           8.0
       6           7.0
       15          8.0
       16          6.0
       18          8.0
...                ...
       31764       7.0
       31964       8.0
       32093       8.0
       32182       9.0
       32282       9.0

[449 rows x 1 columns]

In [91]:
recm.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 449 entries, ('rating', 1) to ('rating', 32282)
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   60185   449 non-null    float64
dtypes: float64(1)
memory usage: 18.4+ KB

In [79]:
pd.read_csv?

Signature:
pd.read_csv(
    filepath_or_buffer: 'FilePath | ReadCsvBuffer[bytes] | ReadCsvBuffer[str]',
    *,
    sep: 'str | None | lib.NoDefault' = <no_default>,
    delimiter: 'str | None | lib.NoDefault' = None,
    header: "int | Sequence[int] | None | Literal['infer']" = 'infer',
    names: 'Sequence[Hashable] | None | lib.NoDefault' = <no_default>,
    index_col: 'IndexLabel | Literal[False] | None' = None,
    usecols=None,
    dtype: 'DtypeArg | None' = None,
    engine: 'CSVEngine | None' = None,
    converters=None,
    true_values=None,
    false_values=None,
    skipinitialspace: 'bool' = False,
    skiprows=None,
    skipfooter: 'int' = 0,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    skip_blank_lines: 'bool' = True,
    parse_dates: 'bool | Sequence[Hashable] | None' = None,
    infer_datetime_format: 'bool | lib.NoDefault' = <no_default>,
    keep_date_col: 'bool' = False,
    date_parser=<no_default>,
    date_format: 'str | None' = None,
    dayfirst: 'bool' = False,
    cache_dates: 'bool' = True,
    iterator: 'bool' = False,
    chunksize: 'int | None' = None,
    compression: 'CompressionOptions' = 'infer',
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    lineterminator: 'str | None' = None,
    quotechar: 'str' = '"',
    quoting: 'int' = 0,
    doublequote: 'bool' = True,
    escapechar: 'str | None' = None,
    comment: 'str | None' = None,
    encoding: 'str | None' = None,
    encoding_errors: 'str | None' = 'strict',
    dialect: 'str | csv.Dialect | None' = None,
    on_bad_lines: 'str' = 'error',
    delim_whitespace: 'bool' = False,
    low_memory=True,
    memory_map: 'bool' = False,
    float_precision: "Literal['high', 'legacy'] | None" = None,
    storage_options: 'StorageOptions' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
) -> 'DataFrame | TextFileReader'
Docstring:
Read a comma-separated values (csv) file into DataFrame.

Also supports optionally iterating or breaking of the file
into chunks.

Additional help can be found in the online docs for
`IO Tools <https://pandas.pydata.org/pandas-docs/stable/user_guide/io.html>`_.

Parameters
----------
filepath_or_buffer : str, path object or file-like object
    Any valid string path is acceptable. The string could be a URL. Valid
    URL schemes include http, ftp, s3, gs, and file. For file URLs, a host is
    expected. A local file could be: file://localhost/path/to/table.csv.

    If you want to pass in a path object, pandas accepts any ``os.PathLike``.

    By file-like object, we refer to objects with a ``read()`` method, such as
    a file handle (e.g. via builtin ``open`` function) or ``StringIO``.
sep : str, default ','
    Delimiter to use. If sep is None, the C engine cannot automatically detect
    the separator, but the Python parsing engine can, meaning the latter will
    be used and automatically detect the separator by Python's builtin sniffer
    tool, ``csv.Sniffer``. In addition, separators longer than 1 character and
    different from ``'\s+'`` will be interpreted as regular expressions and
    will also force the use of the Python parsing engine. Note that regex
    delimiters are prone to ignoring quoted data. Regex example: ``'\r\t'``.
delimiter : str, default ``None``
    Alias for sep.
header : int, list of int, None, default 'infer'
    Row number(s) to use as the column names, and the start of the
    data.  Default behavior is to infer the column names: if no names
    are passed the behavior is identical to ``header=0`` and column
    names are inferred from the first line of the file, if column
    names are passed explicitly then the behavior is identical to
    ``header=None``. Explicitly pass ``header=0`` to be able to
    replace existing names. The header can be a list of integers that
    specify row locations for a multi-index on the columns
    e.g. [0,1,3]. Intervening rows that are not specified will be
    skipped (e.g. 2 in this example is skipped). Note that this
    parameter ignores commented lines and empty lines if
    ``skip_blank_lines=True``, so ``header=0`` denotes the first line of
    data rather than the first line of the file.
names : array-like, optional
    List of column names to use. If the file contains a header row,
    then you should explicitly pass ``header=0`` to override the column names.
    Duplicates in this list are not allowed.
index_col : int, str, sequence of int / str, or False, optional, default ``None``
  Column(s) to use as the row labels of the ``DataFrame``, either given as
  string name or column index. If a sequence of int / str is given, a
  MultiIndex is used.

  Note: ``index_col=False`` can be used to force pandas to *not* use the first
  column as the index, e.g. when you have a malformed file with delimiters at
  the end of each line.
usecols : list-like or callable, optional
    Return a subset of the columns. If list-like, all elements must either
    be positional (i.e. integer indices into the document columns) or strings
    that correspond to column names provided either by the user in `names` or
    inferred from the document header row(s). If ``names`` are given, the document
    header row(s) are not taken into account. For example, a valid list-like
    `usecols` parameter would be ``[0, 1, 2]`` or ``['foo', 'bar', 'baz']``.
    Element order is ignored, so ``usecols=[0, 1]`` is the same as ``[1, 0]``.
    To instantiate a DataFrame from ``data`` with element order preserved use
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['foo', 'bar']]`` for columns
    in ``['foo', 'bar']`` order or
    ``pd.read_csv(data, usecols=['foo', 'bar'])[['bar', 'foo']]``
    for ``['bar', 'foo']`` order.

    If callable, the callable function will be evaluated against the column
    names, returning names where the callable function evaluates to True. An
    example of a valid callable argument would be ``lambda x: x.upper() in
    ['AAA', 'BBB', 'DDD']``. Using this parameter results in much faster
    parsing time and lower memory usage.
dtype : Type name or dict of column -> type, optional
    Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32,
    'c': 'Int64'}
    Use `str` or `object` together with suitable `na_values` settings
    to preserve and not interpret dtype.
    If converters are specified, they will be applied INSTEAD
    of dtype conversion.

    .. versionadded:: 1.5.0

        Support for defaultdict was added. Specify a defaultdict as input where
        the default determines the dtype of the columns which are not explicitly
        listed.
engine : {'c', 'python', 'pyarrow'}, optional
    Parser engine to use. The C and pyarrow engines are faster, while the python engine
    is currently more feature-complete. Multithreading is currently only supported by
    the pyarrow engine.

    .. versionadded:: 1.4.0

        The "pyarrow" engine was added as an *experimental* engine, and some features
        are unsupported, or may not work correctly, with this engine.
converters : dict, optional
    Dict of functions for converting values in certain columns. Keys can either
    be integers or column labels.
true_values : list, optional
    Values to consider as True in addition to case-insensitive variants of "True".
false_values : list, optional
    Values to consider as False in addition to case-insensitive variants of "False".
skipinitialspace : bool, default False
    Skip spaces after delimiter.
skiprows : list-like, int or callable, optional
    Line numbers to skip (0-indexed) or number of lines to skip (int)
    at the start of the file.

    If callable, the callable function will be evaluated against the row
    indices, returning True if the row should be skipped and False otherwise.
    An example of a valid callable argument would be ``lambda x: x in [0, 2]``.
skipfooter : int, default 0
    Number of lines at bottom of file to skip (Unsupported with engine='c').
nrows : int, optional
    Number of rows of file to read. Useful for reading pieces of large files.
na_values : scalar, str, list-like, or dict, optional
    Additional strings to recognize as NA/NaN. If dict passed, specific
    per-column NA values.  By default the following values are interpreted as
    NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
    '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
    'n/a', 'nan', 'null'.
keep_default_na : bool, default True
    Whether or not to include the default NaN values when parsing the data.
    Depending on whether `na_values` is passed in, the behavior is as follows:

    * If `keep_default_na` is True, and `na_values` are specified, `na_values`
      is appended to the default NaN values used for parsing.
    * If `keep_default_na` is True, and `na_values` are not specified, only
      the default NaN values are used for parsing.
    * If `keep_default_na` is False, and `na_values` are specified, only
      the NaN values specified `na_values` are used for parsing.
    * If `keep_default_na` is False, and `na_values` are not specified, no
      strings will be parsed as NaN.

    Note that if `na_filter` is passed in as False, the `keep_default_na` and
    `na_values` parameters will be ignored.
na_filter : bool, default True
    Detect missing value markers (empty strings and the value of na_values). In
    data without any NAs, passing na_filter=False can improve the performance
    of reading a large file.
verbose : bool, default False
    Indicate number of NA values placed in non-numeric columns.
skip_blank_lines : bool, default True
    If True, skip over blank lines rather than interpreting as NaN values.
parse_dates : bool or list of int or names or list of lists or dict, default False
    The behavior is as follows:

    * boolean. If True -> try parsing the index.
    * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
      each as a separate date column.
    * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
      a single date column.
    * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
      result 'foo'

    If a column or index cannot be represented as an array of datetimes,
    say because of an unparsable value or a mixture of timezones, the column
    or index will be returned unaltered as an object data type. For
    non-standard datetime parsing, use ``pd.to_datetime`` after
    ``pd.read_csv``.

    Note: A fast-path exists for iso8601-formatted dates.
infer_datetime_format : bool, default False
    If True and `parse_dates` is enabled, pandas will attempt to infer the
    format of the datetime strings in the columns, and if it can be inferred,
    switch to a faster method of parsing them. In some cases this can increase
    the parsing speed by 5-10x.

    .. deprecated:: 2.0.0
        A strict version of this argument is now the default, passing it has no effect.

keep_date_col : bool, default False
    If True and `parse_dates` specifies combining multiple columns then
    keep the original columns.
date_parser : function, optional
    Function to use for converting a sequence of string columns to an array of
    datetime instances. The default uses ``dateutil.parser.parser`` to do the
    conversion. Pandas will try to call `date_parser` in three different ways,
    advancing to the next if an exception occurs: 1) Pass one or more arrays
    (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
    string values from the columns defined by `parse_dates` into a single array
    and pass that; and 3) call `date_parser` once for each row using one or
    more strings (corresponding to the columns defined by `parse_dates`) as
    arguments.

    .. deprecated:: 2.0.0
       Use ``date_format`` instead, or read in as ``object`` and then apply
       :func:`to_datetime` as-needed.
date_format : str or dict of column -> format, default ``None``
   If used in conjunction with ``parse_dates``, will parse dates according to this
   format. For anything more complex,
   please read in as ``object`` and then apply :func:`to_datetime` as-needed.

   .. versionadded:: 2.0.0
dayfirst : bool, default False
    DD/MM format dates, international and European format.
cache_dates : bool, default True
    If True, use a cache of unique, converted dates to apply the datetime
    conversion. May produce significant speed-up when parsing duplicate
    date strings, especially ones with timezone offsets.

iterator : bool, default False
    Return TextFileReader object for iteration or getting chunks with
    ``get_chunk()``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
chunksize : int, optional
    Return TextFileReader object for iteration.
    See the `IO Tools docs
    <https://pandas.pydata.org/pandas-docs/stable/io.html#io-chunking>`_
    for more information on ``iterator`` and ``chunksize``.

    .. versionchanged:: 1.2

       ``TextFileReader`` is a context manager.
compression : str or dict, default 'infer'
    For on-the-fly decompression of on-disk data. If 'infer' and 'filepath_or_buffer' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    If using 'zip' or 'tar', the ZIP file must contain only one data file to be read in.
    Set to ``None`` for no decompression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'tar'``} and other
    key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdDecompressor`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for Zstandard decompression using a
    custom compression dictionary:
    ``compression={'method': 'zstd', 'dict_data': my_compression_dict}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

    .. versionchanged:: 1.4.0 Zstandard support.

thousands : str, optional
    Thousands separator.
decimal : str, default '.'
    Character to recognize as decimal point (e.g. use ',' for European data).
lineterminator : str (length 1), optional
    Character to break file into lines. Only valid with C parser.
quotechar : str (length 1), optional
    The character used to denote the start and end of a quoted item. Quoted
    items can include the delimiter and it will be ignored.
quoting : int or csv.QUOTE_* instance, default 0
    Control field quoting behavior per ``csv.QUOTE_*`` constants. Use one of
    QUOTE_MINIMAL (0), QUOTE_ALL (1), QUOTE_NONNUMERIC (2) or QUOTE_NONE (3).
doublequote : bool, default ``True``
   When quotechar is specified and quoting is not ``QUOTE_NONE``, indicate
   whether or not to interpret two consecutive quotechar elements INSIDE a
   field as a single ``quotechar`` element.
escapechar : str (length 1), optional
    One-character string used to escape other characters.
comment : str, optional
    Indicates remainder of line should not be parsed. If found at the beginning
    of a line, the line will be ignored altogether. This parameter must be a
    single character. Like empty lines (as long as ``skip_blank_lines=True``),
    fully commented lines are ignored by the parameter `header` but not by
    `skiprows`. For example, if ``comment='#'``, parsing
    ``#empty\na,b,c\n1,2,3`` with ``header=0`` will result in 'a,b,c' being
    treated as the header.
encoding : str, optional, default "utf-8"
    Encoding to use for UTF when reading/writing (ex. 'utf-8'). `List of Python
    standard encodings
    <https://docs.python.org/3/library/codecs.html#standard-encodings>`_ .

    .. versionchanged:: 1.2

       When ``encoding`` is ``None``, ``errors="replace"`` is passed to
       ``open()``. Otherwise, ``errors="strict"`` is passed to ``open()``.
       This behavior was previously only the case for ``engine="python"``.

    .. versionchanged:: 1.3.0

       ``encoding_errors`` is a new argument. ``encoding`` has no longer an
       influence on how encoding errors are handled.

encoding_errors : str, optional, default "strict"
    How encoding errors are treated. `List of possible values
    <https://docs.python.org/3/library/codecs.html#error-handlers>`_ .

    .. versionadded:: 1.3.0

dialect : str or csv.Dialect, optional
    If provided, this parameter will override values (default or not) for the
    following parameters: `delimiter`, `doublequote`, `escapechar`,
    `skipinitialspace`, `quotechar`, and `quoting`. If it is necessary to
    override values, a ParserWarning will be issued. See csv.Dialect
    documentation for more details.
on_bad_lines : {'error', 'warn', 'skip'} or callable, default 'error'
    Specifies what to do upon encountering a bad line (a line with too many fields).
    Allowed values are :

        - 'error', raise an Exception when a bad line is encountered.
        - 'warn', raise a warning when a bad line is encountered and skip that line.
        - 'skip', skip bad lines without raising or warning when they are encountered.

    .. versionadded:: 1.3.0

    .. versionadded:: 1.4.0

        - callable, function with signature
          ``(bad_line: list[str]) -> list[str] | None`` that will process a single
          bad line. ``bad_line`` is a list of strings split by the ``sep``.
          If the function returns ``None``, the bad line will be ignored.
          If the function returns a new list of strings with more elements than
          expected, a ``ParserWarning`` will be emitted while dropping extra elements.
          Only supported when ``engine="python"``

delim_whitespace : bool, default False
    Specifies whether or not whitespace (e.g. ``' '`` or ``'    '``) will be
    used as the sep. Equivalent to setting ``sep='\s+'``. If this option
    is set to True, nothing should be passed in for the ``delimiter``
    parameter.
low_memory : bool, default True
    Internally process the file in chunks, resulting in lower memory use
    while parsing, but possibly mixed type inference.  To ensure no mixed
    types either set False, or specify the type with the `dtype` parameter.
    Note that the entire file is read into a single DataFrame regardless,
    use the `chunksize` or `iterator` parameter to return the data in chunks.
    (Only valid with C parser).
memory_map : bool, default False
    If a filepath is provided for `filepath_or_buffer`, map the file object
    directly onto memory and access the data directly from there. Using this
    option can improve performance because there is no longer any I/O overhead.
float_precision : str, optional
    Specifies which converter the C engine should use for floating-point
    values. The options are ``None`` or 'high' for the ordinary converter,
    'legacy' for the original lower precision pandas converter, and
    'round_trip' for the round-trip converter.

    .. versionchanged:: 1.2

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

    .. versionadded:: 1.2

dtype_backend : {"numpy_nullable", "pyarrow"}, defaults to NumPy backed DataFrames
    Which dtype_backend to use, e.g. whether a DataFrame should have NumPy

In [98]:
recm.reset_index(inplace=True)

In [99]:
recm

    level_0  anime_id  60185
0    rating         1    8.0
1    rating         6    7.0
2    rating        15    8.0
3    rating        16    6.0
4    rating        18    8.0
..      ...       ...    ...
444  rating     31764    7.0
445  rating     31964    8.0
446  rating     32093    8.0
447  rating     32182    9.0
448  rating     32282    9.0

[449 rows x 3 columns]

In [102]:
recm.drop('level_0', axis=1, inplace=True)

In [109]:
recm.rename(columns={60185: 'Ratings'}, inplace=True)

In [110]:
recm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 449 entries, 0 to 448
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  449 non-null    int64
 1   Ratings   449 non-null    float64
dtypes: float64(1), int64(1)
memory usage: 7.1 KB

In [128]:
recm.set_index(['anime_id'], inplace=True)

KeyError: "None of ['anime_id'] are in the columns"

In [129]:
recm

          Ratings
anime_id
1             8.0
6             7.0
15            8.0
16            6.0
18            8.0
...           ...
31764         7.0
31964         8.0
32093         8.0
32182         9.0
32282         9.0

[449 rows x 1 columns]

In [131]:
id=recm.loc[recm['Ratings']>=10].index
id

Index([   44,   164,   245,   263,  2104,  2418,  3702,  4155,  4654,  5028,
        5114, 11061, 12859, 15323, 28977],
      dtype='int64', name='anime_id')

In [116]:
anime = pd.read_csv('/Users/owais/Jupyter Notebook/archive-2/anime.csv')

In [117]:
anime

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,GintamaÂ°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266
...,...,...,...,...,...,...,...
12289,9316,Toushindai My Lover: Minami tai Mecha-Minami,Hentai,OVA,1,4.15,211
12290,5543,Under World,Hentai,OVA,1,4.28,183
12291,5621,Violence Gekiga David no Hoshi,Hentai,OVA,4,4.88,219
12292,6133,Violence Gekiga Shin David no Hoshi: Inma Dens...,Hentai,OVA,1,4.98,175
12293,26081,Yasuji no Pornorama: Yacchimae!!,Hentai,Movie,1,5.46,142

In [132]:
recommendations = anime[anime["anime_id"].isin(id)]

In [135]:
recommendations

,anime_id,name,genre,type,episodes,rating,members
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,GintamaÂ°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
20,263,Hajime no Ippo,"Comedy, Drama, Shounen, Sports",TV,75,8.83,157670
21,44,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,"Action, Drama, Historical, Martial Arts, Roman...",OVA,4,8.83,129307
24,164,Mononoke Hime,"Action, Adventure, Fantasy",Movie,1,8.81,339556
30,245,Great Teacher Onizuka,"Comedy, Drama, School, Shounen, Slice of Life",TV,43,8.77,268487
73,5028,Major S5,"Comedy, Drama, Romance, Sports",TV,25,8.58,28653
136,2418,Stranger: Mukou Hadan,"Action, Adventure, Historical, Samurai",Movie,1,8.43,125503
143,4155,One Piece Film: Strong World,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.42,85020
163,12859,One Piece Film: Z,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.39,76051
241,15323,One Piece: Episode of Nami - Koukaishi no Nami...,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Special,1,8.27,24707
245,3702,Detroit Metal City,"Comedy, Music",OVA,12,8.26,104893
597,2104,Seto no Hanayome,"Comedy, Parody, Romance, School",TV,26,7.95,165008
1096,4654,Toaru Majutsu no Index,"Action, Magic, Sci-Fi, Super Power",TV,24,7.69,313114

In [160]:
recommendations[~recommendations["anime_id"].isin(aw)]

,anime_id,name,genre,type,episodes,rating,members
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,GintamaÂ°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
6,11061,Hunter x Hunter (2011),"Action, Adventure, Shounen, Super Power",TV,148,9.13,425855
21,44,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,"Action, Drama, Historical, Martial Arts, Roman...",OVA,4,8.83,129307
24,164,Mononoke Hime,"Action, Adventure, Fantasy",Movie,1,8.81,339556
73,5028,Major S5,"Comedy, Drama, Romance, Sports",TV,25,8.58,28653
143,4155,One Piece Film: Strong World,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.42,85020
163,12859,One Piece Film: Z,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Movie,1,8.39,76051
241,15323,One Piece: Episode of Nami - Koukaishi no Nami...,"Action, Adventure, Comedy, Drama, Fantasy, Sho...",Special,1,8.27,24707

In [154]:
len(aw)

1720

In [ ]:
len(common_movie)

In [ ]:
#cosine score array
c = np.array(score).T

In [ ]:
c

In [ ]:
min(c)

In [ ]:
result = list(filter(lambda x: x < 0.4, c))
result

In [ ]:
# l = len(c)
# condidate = []
# for i in range(l):
#     #p = []
#     if c[i]<0.4:
#         condidate.append(common_movie.iloc[[i]])
#     #p.append(condidate)

In [ ]:
# Find the minimum value in the list c
min_c = min(c)

# Create a list to store candidate rows from common_movie
candidates = []

# Iterate through the indices and values in c
for i, value in enumerate(c):
    # Check if the value is equal to the minimum value
    if value == 0.3211557666978694:
        # Append the corresponding row from common_movie to candidates
        candidates.append(common_movie.iloc[[i]])

# candidates now contains rows from common_movie with the lowest value in c

In [ ]:
condidate

In [ ]:
candidates

In [ ]:
common_movie.iloc[[1]]

In [ ]:
common_movie

In [ ]:
h = np.array(candidates[0])
h=h.ravel()

In [ ]:
h

<h2>Result of recommender example</h2>

In [ ]:
l = len(h)
recommender = []
for i in range(l):
    if h[i]!=0:
        recommender.append(list_m[i])
        
recommender